### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zhangchao77** [danfenghong/IEEE_TGRS_SpectralFormer#3]
TR = data['TR']
TE = data['TE']
# TR = data['pavia']
# TE = data_gt['pavia_gt']
label = TR + TE
老师您好，您这里我没有看懂什么意思？有关TR和

**Comment by zhangchao77** [comment]
有关TR和TE

**Comment by danfenghong** [comment]
TR是指训练数据，TE是测试数据

zhangchao77 ***@***.***> 于2021年11月26日周五 下午10:00写道：

**Comment by zhangchao77** [comment]
> TR = data['TR'] TE = data['TE']
> 
> # TR = data['pavia']
> # TE = data_gt['pavia_gt']
> label = TR + TE 老师您好，您这里我没有看懂什么意思？有关TR和
